///////////////////////////////////////////////////////////
//  Administrator.cs
//  Implementation of the Class Administrator
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2023 8:57:09 PM
//  Original author: dell xps
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Administrator : Personne {

	public int id { get; set; }

}//end Administrator