///////////////////////////////////////////////////////////
//  Grade.cs
//  Implementation of the Class Grade
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2023 8:57:09 PM
//  Original author: dell xps
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Grade {

	public double drade { get; set; }
    public int id;
	public Student m_student { get; set; }
    public Subject m_subject { get; set; }

    

}//end Grade