///////////////////////////////////////////////////////////
//  Personne.cs
//  Implementation of the Class Personne
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2023 8:57:09 PM
//  Original author: dell xps
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using GestionScolarité.Models;

public class Personne {

	public string adress { get; set; }
    public string birthDate { get; set; }
    public string cin { get; set; }
    public string email { get; set; }
    public string firstName { get; set; }
    public string id { get; set; }
    public int lastName { get; set; }
    public string phone { get; set; }
    public Account m_account { get; set; }



}//end Personne