///////////////////////////////////////////////////////////
//  section.cs
//  Implementation of the Class section
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2023 8:57:09 PM
//  Original author: dell xps
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Section {

	public int id { get; set; }
    public int level { get; set; }
    public string name { get; set; }
    public Student[] m_student { get; set; }



}//end section