///////////////////////////////////////////////////////////
//  student.cs
//  Implementation of the Class student
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2023 8:57:09 PM
//  Original author: dell xps
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Student : Personne {

	public int id { get; set; }
    public int matricule { get; set; }
    public bool status { get; set; }
    public Section section  { get; set; }
   

}//end student