///////////////////////////////////////////////////////////
//  subject.cs
//  Implementation of the Class subject
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2023 8:57:10 PM
//  Original author: dell xps
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Subject {

	public int id { get; set; }
    public string name { get; set; }

}//end subject